// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models;

public partial class ChatMessage
{
    public int MessageId { get; set; }

    public Guid SenderId { get; set; }

    public Guid ReceivedId { get; set; }

    public string MessageText { get; set; }

    public DateTime SentAt { get; set; }

    public virtual User Received { get; set; }

    public virtual User Sender { get; set; }
}