// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models;

public partial class ForumComment
{
    public int CommentId { get; set; }

    public int PostId { get; set; }

    public Guid UserId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ForumPost Post { get; set; }

    public virtual User User { get; set; }
}