// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models;

public partial class ProgressRecord
{
    public int ProgressId { get; set; }

    public int PlanId { get; set; }

    public DateOnly RecordDate { get; set; }

    public int CigarettesSmoked { get; set; }

    public string HealthStatus { get; set; }

    public string Notes { get; set; }

    public virtual QuitPlan Plan { get; set; }
}