// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class CoachSession
{
    public int SessionId { get; set; }

    public Guid UserId { get; set; }

    public Guid CoachId { get; set; }

    public DateTime ScheduledAt { get; set; }

    public string Status { get; set; }

    public string SessionNotes { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual User Coach { get; set; }

    public virtual User User { get; set; }
}