// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class MembershipPackage
{
    public int PackageId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public int DurationDays { get; set; }

    public string Description { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}