// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class Notification
{
    public int NotificationId { get; set; }

    public Guid UserId { get; set; }

    public string NotifType { get; set; }

    public string Content { get; set; }

    public DateTime ScheduledTime { get; set; }

    public DateTime? SentAt { get; set; }

    public string Status { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User User { get; set; }
}