// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class ProgressRecord
{
    public int ProgressId { get; set; }

    public int PlanId { get; set; }

    public DateOnly RecordDate { get; set; }

    public int CigarettesSmoked { get; set; }

    public string HealthStatus { get; set; }

    public string Notes { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual QuitPlan Plan { get; set; }
}