// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class SmokingRecord
{
    public int RecordId { get; set; }

    public Guid UserId { get; set; }

    public DateOnly RecordDate { get; set; }

    public int CigarettesCount { get; set; }

    public string Frequency { get; set; }

    public decimal? CostPerPack { get; set; }

    public string Notes { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User User { get; set; }
}