// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject;

public partial class UserBadge
{
    public int UserBadgeId { get; set; }

    public Guid UserId { get; set; }

    public int BadgeId { get; set; }

    public DateTime AwardedAt { get; set; }

    public bool? Disabled { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Badge Badge { get; set; }

    public virtual User User { get; set; }
}